version: "3.9"

services:
  mysql: # Servicio de base de datos MySQL
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb
      MYSQL_USER: app
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  app: # Servicio de la aplicaci√≥n Go
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=app
      - DB_PASSWORD=apppass
      - DB_NAME=appdb
      - TIMEZONE=America/Puerto_Rico
      - TARGET_URL=https://billing.osnetpr.com/admin/reports/report_billings_detail.php?type=&begin=%d&end=%d&type=
      - TABLE_SELECTOR=table.table-body-modern
      - ROW_SELECTOR=tr
    env_file:
      - .env
    volumes:
      - ./migrations:/migrations
      - ./goose-db.yaml:/goose-db.yaml
    entrypoint: ["/root/entrypoint.sh"]
    restart: "no"

volumes:
  db_data:
