services:
  mysql: # Servicio de base de datos MySQL
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb
      MYSQL_USER: app
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"] # Comando para verificar el estado de MySQL
      interval: 10s # Verifica cada 10 segundos
      retries: 5  # Espera a que MySQL esté listo antes de iniciar la app

  app: # Servicio de la aplicación Go
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=app
      - DB_PASSWORD=apppass
      - DB_NAME=appdb
      - TIMEZONE=America/Puerto_Rico
      - TARGET_URL=https://billing.osnetpr.com/admin/reports/report_billings_detail.php?type=&begin=%d&end=%d&type=
      - TABLE_SELECTOR=table.table-body-modern
      - ROW_SELECTOR=tr 
    env_file:
      - .env

    # volumes:
    #   - ./:/app
    restart: "no" # Cambia a "always" para producción

volumes: 
  db_data: 
